### ISSUE TITLE
Do you have a docker-compose.yml ? 

### ISSUE THREAD

**Issue by Inv0k-er** [javanile/myddleware#1]
Sorry I saw your image in Docker Hub [https://hub.docker.com/r/javanile/myddleware/dockerfile](https://hub.docker.com/r/javanile/myddleware/dockerfile)
Do you have a docker-compose.yml ?

**Comment by francescobianco** [comment]
@Inv0k-er This is a work in progress project! Are you interested to develop with myddleware or just use it?

**Comment by Inv0k-er** [comment]
No it is just my interest. Because I want to deploy in docker.
